# Generated by Django 4.1.4 on 2023-08-19 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0002_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='rating',
            field=models.ManyToManyField(related_name='user_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
