# Generated by Django 4.1.4 on 2023-08-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0004_remove_cookie_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='cookies',
            new_name='cookie',
        ),
    ]
